version: '3.8'
services:
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - 80:80
        networks:
            - dashboard-net
        depends_on:
            - app
    cron-downloader:
        container_name: cron
        build:
            context: .
            dockerfile: cron/Dockerfile
        environment:
            - DATABASE_URL=${DATABASE_URL:-sqlite:////data/trades.db}
        volumes:
            - data:/data
    app:
        container_name: flask
        build:
            context: .
            dockerfile: dashboard/Dockerfile

        command: gunicorn --reload --bind 0.0.0.0:5000 --workers 4 "src.app:create_app()"
        environment:
            - FLASK_APP=src/app.py
            - FLASK_ENV=${FLASK_ENV:-production}
            - DATABASE_URL=${DATABASE_URL:-sqlite:////data/trades.db}
        volumes:
            - data:/data
            - dashboard-src:/code/src
        networks:
            dashboard-net:
                aliases:
                    - flask-dashboard
volumes:
    data:
        driver: local
        driver_opts:
            type: none
            device: $PWD/data
            o: bind
    dashboard-src:
        driver: local
        driver_opts:
            type: none
            device: $PWD/dashboard/src
            o: bind
networks:
    dashboard-net:
