version: '3.8'
services:
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - 80:80
        networks:
            - dashboard-net
        depends_on:
            - app
    app:
        container_name: flask
        build:
            context: .
            dockerfile: dashboard/Dockerfile
        command: gunicorn --reload --bind 0.0.0.0:${PORT:-5000} "wsgi:app"
        environment:
            - PORT=${PORT:-5000}
            - FLASK_APP=wsgi
            - DATABASE_URL=${DATABASE_URL:-sqlite:////data/trades.db}
            - SECRET_KEY=${SECRET_KEY:-dev_only_FyLXFDRhpl}
            - FLASK_ENV=${FLASK_ENV:-development}
            - FLASK_DEBUG=${FLASK_DEBUG:-1}
        volumes:
            - data:/data
            - dashboard-src:/dashboard/src
        networks:
            dashboard-net:
                aliases:
                    - flask-dashboard
volumes:
    data:
        driver: local
        driver_opts:
            type: none
            device: $PWD/data
            o: bind
    dashboard-src:
        driver: local
        driver_opts:
            type: none
            device: $PWD/dashboard/src
            o: bind
networks:
    dashboard-net:
