version: '3.8'
services:
    cron-downloader:
        container_name: cron
        build:
            context: .
            dockerfile: cron/Dockerfile
        volumes:
            - data:/data
    app:
        container_name: flask
        build:
            context: .
            dockerfile: dashboard/Dockerfile
        ports:
            - '5000:5000'
        environment:
            - FLASK_APP=src/app.py
            - FLASK_ENV=${FLASK_ENV:-production}
        volumes:
            - data:/data
            - dashboard-src:/code/src
volumes:
    data:
        driver: local
        driver_opts:
            type: none
            device: $PWD/data
            o: bind
    dashboard-src:
        driver: local
        driver_opts:
            type: none
            device: $PWD/dashboard/src
            o: bind